### ISSUE TITLE
Lando taking +5 min te load and navigate in WordPress on Windows 11

### ISSUE THREAD

**Issue by DylanBracke** [lando/wordpress#31]
**What is your lando version and operating system? (note that the older your version the less likely we are to reply)**
> v3.11.0

**Tell us about your .lando.yml**
```
name: (hidden)
recipe: wordpress
config:
  webroot: .
  php: 7.4
  database: mysql
services:
  phpmyadmin:
    type: phpmyadmin
```
Commands:
```
lando start
```
**Tell us about the error you got**
> It takes a really long time to load +5min, and every navigation after also takes +2 min making it impossible te use.

**Tell us more**
> Windows 11
> cores : 6
> ram : 8GB
