### ISSUE TITLE
Custom NGINX Rules not working in Wordpress Lando Recipe

### ISSUE THREAD

**Issue by asimongm** [lando/wordpress#74]
Hello, 

I try to add specific CORS rules, and a redirection rule (for testing the conf) in a custom nginx config on a wordpress local lando site, but it's not working, my server directives seems to be ignored. Is there something wrong on my files ? 

### Here is my .lando file config : 

```
name: projectname
recipe: wordpress
config:
  php: '8.0'
  via: nginx
  webroot: web
  database: mariadb
  config:
    server: config/nginx.conf
proxy:
  appserver_nginx:
    - projectname.lndo.site
    - projectnameother.lndo.site
  pma:
    - pma.projectname.lndo.site
services:
  appserver_nginx:
    build:
      - composer install
    scanner: false
  node:
    type: node:16
    globals:
      gulp-cli: "latest"
  pma:
    type: phpmyadmin
    hosts:
      - database
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
```

###  And here is my nginx.conf file config :

```
# Based on https://www.nginx.com/resources/wiki/start/topics/examples/full/#nginx-conf
user              root root;  ## Default: nobody

worker_processes  auto;
error_log         "/opt/bitnami/nginx/logs/error.log";
pid               "/opt/bitnami/nginx/tmp/nginx.pid";

events {
    worker_connections  1024;
}

http {
    include       mime.types;

    default_type  application/octet-stream;

    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;

    #add_header 'Access-Control-Allow-Origin' '*';
    client_body_temp_path  "/opt/bitnami/nginx/tmp/client_body" 1 2;
    proxy_temp_path        "/opt/bitnami/nginx/tmp/proxy" 1 2;
    fastcgi_temp_path      "/opt/bitnami/nginx/tmp/fastcgi" 1 2;
    scgi_temp_path         "/opt/bitnami/nginx/tmp/scgi" 1 2;
    uwsgi_temp_path        "/opt/bitnami/nginx/tmp/uwsgi" 1 2;

    log_format    main '$remote_addr - $remote_user [$time_local] '
                       '"$request" $status  $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for"';

    access_log    "/opt/bitnami/nginx/logs/access.log";

    sendfile           on;

    tcp_nopush         on;
    tcp_nodelay        off;

    keepalive_timeout  65;
    gzip               on;
    gzip_http_version  1.0;
    gzip_comp_level    2;
    gzip_proxied       any;
    gzip_types         text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    ssl_protocols      TLSv1 TLSv1.1 TLSv1.2;

    map $http_x_forwarded_proto $lando_https {
      default '';
      https on;
    }

    map $http_x_forwarded_proto $http_user_agent_https {
      default '';
      https ON;
    }

    client_max_body_size 80M;
    server_tokens off;
    include  "/opt/bitnami/nginx/conf/vhosts/*.conf";

    # HTTP Server
    server {
        # port to listen on. Can also be set to an IP:PORT
        listen  8080;

        location ~* \.(eot|otf|ttf|woff|woff2)$ {
            add_header Access-Control-Allow-Origin *;
        }

        location /status {
            stub_status on;
            access_log   off;
            allow 127.0.0.1;
            deny all;
        }

        location /wp-content/uploads/sites/2/2020/11/Ma-Prime-Rénov-violet.pdf {
            return 301 https://www.promotelec.com/particuliers/fiche/la-renovation-a-la-cote-avec-maprimerenov/;
        }
    }
}
```

Thanks for helping !

**Comment by reynoldsalec** [comment]
@asimongm make sure the path to your `nginx.conf` is correct (IE in this case nested in a file `config` within your project root)...otherwise this looks like the correct config to me.

**Comment by pereirinha** [comment]
@asimongm 

Did you find what was wrong here?
I'm getting to the same issue. It's as if the NGINX config file is not used. At least I'm not seeing the changes being applied inside the container, ensuring that I've run the `lando rebuild` beforehand.

**Comment by asimongm** [comment]
Hello ! 

I finally find a correct configuration to apply custum nginx config and php.ini file on a wordpress lando project, here are my files : 

# .lando file

```
name: projectname
recipe: wordpress
config:
  php: '8.0'
  via: nginx:1.18
  xdebug: true
  webroot: web
  database: mariadb
  config:
    php: config/php.ini
    vhosts: config/nginx.conf
proxy:
  appserver_nginx:
    - projectname.lndo.site
  pma:
    - pma.projectname.lndo.site
services:
  node:
    type: node:20
    globals:
      gulp-cli: "latest"
  pma:
    type: phpmyadmin
    hosts:
      - database
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
```

My error on previous configuration was to use "config: server: config/nginx.conf" instead of "config: server: vhosts/nginx.conf".

I also change my nginx config file, like this : 

```
# WordPress single site rules.
# Designed to be included in any server {} block.
# LANDOWORDPRESSNGINXCONF

# Upstream to abstract backend connection(s) for php
upstream php {
  server fpm:9000;
}

server {
    server_name localhost;
    ## Your only path reference.
    root "{{LANDO_WEBROOT}}";
    listen 80 default_server;
    listen 443 ssl;
    ssl_certificate           /certs/cert.crt;
    ssl_certificate_key       /certs/cert.key;
    ssl_verify_client         off;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    port_in_redirect off;

    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; ";
    add_header Access-Control-Allow-Origin "*" always;
    add_header Access-Control-Allow-Credentials "true" always;

    client_max_body_size 100M;

    ## This should be in your http block and if it is, it's not needed here.
    index index.php;

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    location / {
        # This is cool because no php is touched for static content.
        # include the "?$args" part so non-default permalinks doesn't break when using query string
        try_files $uri $uri/ /index.php?q=$uri&$args;
    }

    location ~ \.php$ {
        #NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_TRANSLATED $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_intercept_errors on;
        fastcgi_pass php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires max;
        log_not_found off;
    }

    location ~* \.(flv|ico|avi|mov|ppt|doc|mp3|wmv|wav|mp4|m4v|ogg|webm|aac|eot|ttf|ttc|otf|eot|css|js|woff|woff2|svg|jpg|jpeg|png|gif|swf)$ {
        add_header Access-Control-Allow-Origin "*" always;
    }
}
```
