### ISSUE TITLE
WP Cli no more recognized

### ISSUE THREAD

**Issue by sebastienserre** [lando/wordpress#90]
On Lando 3.23.15, WP CLI is no more recognized

```
sebastien@sebastien-desktop:/media/projets/polylang/support/main$ lando wp info
Usage: lando <command> [args] [options]

Commands:
  lando composer    Runs composer commands
  lando config      Displays the lando configuration
  lando destroy     Destroys your app
  lando exec        Runs command(s) on a service
  lando info        Prints info about your app
  lando init        Fetched code and/or initializes a Landofile for use with lando
  lando list        Lists all running lando apps and containers
  lando logs        Displays logs for your app
  lando mailpit     Shows Mailpit connection information
  lando poweroff    Spins down all lando related containers
  lando rebuild     Rebuilds your app from scratch, preserving data
  lando restart     Restarts your app
  lando start       Starts your app
  lando stop        Stops your app
  lando update      Updates lando
  lando version     Displays lando version information
  lando xdebug-off  Disable xdebug for Apache.
  lando xdebug-on   Enable xdebug for Apache.

Options:
  --channel      Sets the update channel                                                                                   [array] [choices: "edge", "none", "stable"]
  --clear        Clears the lando tasks cache                                                                                                                [boolean]
  --debug        Shows debug output                                                                                                                          [boolean]
  --help         Shows lando or delegated command help if applicable                                                                                         [boolean]
  --verbose, -v  Runs with extra verbosity                                                                                                                     [count]

Examples:
  lando start               Run lando start
  lando rebuild --help      Get help about using the lando rebuild command
  lando destroy -y --debug  Run lando destroy non-interactively and with maximum verbosity
  lando --clear             Clear the lando tasks cache

Did you mean stop?
sebastien@sebastien-desktop:/media/projets/polylang/support/main$ ls -la
total 2668
drwxrwxr-x  8 sebastien sebastien    4096 déc.   4 17:20 .
drwxrwxr-x  5 sebastien sebastien    4096 oct.  28 16:40 ..
-rw-r--r--  1 sebastien sebastien 2379736 nov.  13 08:23 base.sql.gz
-rw-rw-r--  1 sebastien sebastien     177 sept.  3 16:00 composer.json
-rw-rw-r--  1 sebastien sebastien   11408 sept.  3 16:00 composer.lock
-rw-rw-r--  1 sebastien sebastien      74 févr. 28  2024 cron.txt
-rw-r--r--  1 sebastien sebastien     523 nov.  13 13:45 .htaccess
drwxrwxr-x  6 sebastien sebastien    4096 déc.   6 18:03 .idea
-rw-r--r--  1 sebastien sebastien     405 févr.  6  2020 index.php
-rw-rw-r--  1 sebastien sebastien      17 août   7 19:16 info.php
-rwxrwxr-x  1 sebastien sebastien    1430 nov.  11 11:57 .lando.yml
-rw-r--r--  1 sebastien sebastien   19915 nov.  19 10:31 license.txt
-rw-r--r--  1 sebastien sebastien   28893 mars  19  2024 logfile.txt
drwxrwxr-x 20 sebastien sebastien    4096 sept. 12 18:22 node_modules
-rw-rw-r--  1 sebastien sebastien      50 sept. 12 18:22 package.json
-rw-rw-r--  1 sebastien sebastien    7710 sept. 12 18:22 package-lock.json
-rw-rw-r--  1 sebastien sebastien      17 janv. 12  2022 phpinfo.php
-rw-rw-r--  1 sebastien sebastien     323 août   7 20:27 php.ini
-rw-r--r--  1 sebastien sebastien    7409 nov.  21 16:36 readme.html
-rw-r--r--  1 sebastien sebastien     194 avril  2  2024 robots.txt
drwxrwxr-x  2 sebastien sebastien    4096 août   7 19:40 .vscode
-rw-r--r--  1 sebastien sebastien    7387 avril 15  2024 wp-activate.php
drwxr-xr-x  9 sebastien sebastien    4096 avril  9  2024 wp-admin
-rw-r--r--  1 sebastien sebastien     351 févr.  6  2020 wp-blog-header.php
-rw-r--r--  1 sebastien sebastien    2323 juin  14  2023 wp-comments-post.php
-rw-rw-r--  1 sebastien sebastien    3876 oct.  16 11:21 wp-config.php
-rw-r--r--  1 sebastien sebastien    3336 nov.  19 10:31 wp-config-sample.php
drwxrwxr-x 11 sebastien sebastien    4096 déc.   6 10:58 wp-content
-rw-r--r--  1 sebastien sebastien    5617 nov.  19 10:31 wp-cron.php
drwxr-xr-x 30 sebastien sebastien   12288 nov.  13 07:28 wp-includes
-rw-r--r--  1 sebastien sebastien    2502 nov.  26  2022 wp-links-opml.php
-rw-r--r--  1 sebastien sebastien    3937 août   9 12:47 wp-load.php
-rw-r--r--  1 sebastien sebastien   51367 nov.  19 10:31 wp-login.php
-rw-r--r--  1 sebastien sebastien    8543 nov.  19 10:31 wp-mail.php
-rw-r--r--  1 sebastien sebastien   29032 nov.  19 10:31 wp-settings.php
-rw-r--r--  1 sebastien sebastien   34385 juin  19  2023 wp-signup.php
-rw-r--r--  1 sebastien sebastien    5102 nov.  19 10:31 wp-trackback.php
-rw-r--r--  1 sebastien sebastien    3246 avril 15  2024 xmlrpc.php
sebastien@sebastien-desktop:/media/projets/polylang/support/main$ 

```

My Lando file: 
```
name: helpdesk-polylang
recipe: wordpress
config:
  webroot: .
  database: mariadb
  php: '8.2'
  mariadb: '10.6'
  xdebug: true
  config:
    php: ./php.ini
services:
  appserver:
    overrides:
      environment:
        XDEBUG_MODE:
  pma:
    type: phpmyadmin
    ssl: true
    sslExpose: false
    hosts:
      - database
  mailpit:
    type: mailpit
    mailFrom:
      - appserver
tooling:
  composer:
    service: appserver
  xdebug-on:
    service: appserver
    description: Enable xdebug for Apache.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && docker-php-ext-enable xdebug && /etc/init.d/apache2 reload && echo "Xdebug enabled"
    user: root

  xdebug-off:
    service: appserver
    description: Disable xdebug for Apache.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload && echo "Xdebug disabled"
    user: root
proxy:
  appserver:
    - url1.lndo.site
    - url2.lndo.site
    - url3.lndo.site
    - url4.lndo.site
    - english-website.lndo.site
    - french-website.lndo.site
    - spanish-website.lndo.site
    - italian-website.lndo.site
    - en.helpdesk-polylang.lndo.site
    - fr.helpdesk-polylang.lndo.site
    - es.helpdesk-polylang.lndo.site
    - subdomain1.helpdesk-polylang.lndo.site
    - subdomain2.helpdesk-polylang.lndo.site
  pma:
    - pma-helpdesk-polylang.lndo.site
  mailpit:
    - mailpit.helpdesk-polylang.lndo.site
```

 https://github.com/lando/wordpress/issues/15#issuecomment-1191650871 fixes the issue.
