### ISSUE TITLE
Lando Configuration Exemple to use Varnish on local Wordpress site

### ISSUE THREAD

**Issue by asimongm** [lando/wordpress#92]
Hello ! 
I'm trying to use Varnish on a local site with wordpress recipe, but I did not find the correct way to do it with apache.

Could you give an exemple of how to make it works ? In Varnish doc they ask to change Apache port to 8080, but when I try to do it on lando, the site is not working, so I don't understund how to make it.  

Could you help me to configure my lando in a correct way to test Varnish on local site ?

Here is my .lando.yml config : 

```
name: mysite
recipe: wordpress
config:
  php: '8.2'
  via: apache
  webroot: web
  ssl: false
  database: mysql:5.7
  xdebug: true
proxy:
  appserver:
    - mysite.lndo.site
  mailhog:
    - mail.mysite.lndo.site
  pma:
    - pma.mysite.lndo.site
services:
  varnish:
    type: varnish
    backend_port: 80
    portforward: true
    backends:
      - appserver
    build_as_root:
      - apt-get update
      - apt-get install -y varnish
    config:
        vcl: config/default.vcl
  appserver:
    build:
      - composer install
    scanner: false
    build_as_root:
      - a2enmod headers
    overrides:
      environment:
        VARNISH_HOST: varnish
        VARNISH_PORT: 80
  node:
    type: node:16
    globals:
      gulp-cli: "latest"
  mailhog:
    scanner: false
    type: mailhog
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts:
      - database
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
  varnish:
    service: varnish
``` 

Thank you !

**Comment by reynoldsalec** [comment]
Looking at this older issue, it almost looks like assigning the `backend_port` may not be necessary; see if the config here works for you: https://github.com/lando/lando/issues/739#issuecomment-377456420

**Comment by AaronFeledy** [comment]
This works for me:
```yaml
name: mysite
recipe: wordpress
services:
  edge:
    type: varnish:6
proxy:
  edge:
    - edge.mysite.lndo.site
```
